apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: hashicorp/vault:1.8.0
          ports:
            - containerPort: 8200