apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: production
spec:
  replicas: 2
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      app: prometheus
  storage:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 50Gi
  resources:
    requests:
      memory: 400Mi
      cpu: "500m"
    limits:
      memory: 800Mi
      cpu: "1000m"
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 2000
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: prometheus-additional.yaml