apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: production
type: Opaque
data:
  dbname: cG9zdGdyZXM=  # base64 encoded "postgres"
  username: cG9zdGdyZXM=  # base64 encoded "postgres"
  password: cGFzc3dvcmQ=  # base64 encoded "password"